name: solace-queue
description: create a queue
inputs:
  endpoint:
    description: Base path to the config API
    required: true
  vpnname:
    description: Message VPN Name
    required: true
  username:
    description: Management Username
    required: true
  password:
    description: Management Password
    required: true
  queuename:
    description: Queue Name
    required: true
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: docker
  image: Dockerfile
  env:
    ENDPOINT: "${{ inputs.endpoint }}"
    VPNNAME: "${{ inputs.vpnname }}"
    USERNAME: "${{ inputs.username }}"
    PASSWORD: "${{ inputs.password }}"
    QUEUENAME: "${{ inputs.queuename }}"
