on: [push]

jobs:
  create:
    runs-on: ubuntu-latest
    name: create a queue called test
    steps:
      - name: Create a queue called hello
        id: create
        uses: hholst80/solace-queue@v1
        with:
          endpoint: https://mr-connection-f3ix458uixl.messaging.solace.cloud:943/SEMP/v2/config
          vpnname: hholst-aws-fra-eks
          username: hholst-aws-fra-eks-admin
          password: 5kqmok678k76ii0l0rc50nmg6g
          queuename: hello
      - name: echo the HTTP response code
        run: echo "The response was ${{ steps.create.outputs.response }}"
